name: Spellchecker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: GitHub Spellcheck Action
        uses: rojopolis/spellcheck-github-actions@0.5.0
